Repository IntellectualSites/Arkitektonika, pull requests merged in 2022-08, with the labels that each got.

#15 Use typescript + cleanup data
  .dockerignore
  .github/workflows/build.yml
  .gitignore
  .yarnrc.yml
  Dockerfile
  README.md
  app/Arkitektonika.ts
  app/Logger.ts
  app/app.js
  app/bin/prune.js
  app/bin/www.js
  app/config.js
  app/config/Config.ts
  app/http/ArkitektonikaServer.ts
  app/http/Response.ts
  app/http/routes/DeleteRouter.ts
  app/http/routes/DownloadRouter.ts
  app/http/routes/IndexRouter.ts
  app/http/routes/UploadRouter.ts
  app/launch.ts
  app/model/SchematicRecord.d.ts
  app/routes/delete.js
  app/routes/download.js
  app/routes/index.js
  app/routes/upload.js
  app/storage/Database.ts
  app/storage/IDataStorage.ts
  app/util/database.js
  app/util/filesystem.js
  app/util/nbt.js
  endpoints.yml
  nodemon.json
  package.json
  tsconfig.json
  yarn.lock
Labels: Major feature

#26 fix: use ts-node-esm instead of ts-node
  README.md
  package.json
Labels: Bugfix

#25 ci: Publish docker images on release
  .github/workflows/publish-docker-image.yml
Labels: chore

#29 build: Run yarn dedupe
  yarn.lock
Labels: dependencies

#30 Bump version to snapshot
  package.json
Labels: skip-changelog

#31 ci: Publish to GH packages too
  .github/workflows/publish-docker-image.yml
Labels: enhancement

#32 docs: Update docker description in README
  README.md
Labels: documentation, chore

#38 Add OCI metadata spec
  Dockerfile
  README.md
Labels: chore
